# Copyright (c) 2023 Real-Time Development Center (RTDC) Project
# All rights reserved.

# ROS Message that represents the four range to bottom beams available for the Teledyne Marine RD Instruments
# Doppler Velocity Logger (DVL)
float32 beam1 #Beam 1 range to bottom in meters.
float32 beam2 #Beam 2 range to bottom in meters.
float32 beam3 #Beam 3 range to bottom in meters.
float32 beam4 #Beam 4 range to bottom in meters.